spring.application.name=rapiffy-backend

## MySQL DataSource
#spring.datasource.url=jdbc:mysql://localhost:3306/rapiffy?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=123
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MySQL DataSource (ServerByt External DB)
spring.datasource.url=jdbc:mysql://mysql.gb.stackcp.com:41097/rapiffy-35303233229f?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=rapiffy-35303233229f
spring.datasource.password=A1qaz2wsx@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# Server port
server.port=8080

# JWT
jwt.secret=rapiffy-super-secret-key-must-be-at-least-32-chars!!
jwt.expiration-ms=86400000

# Google OAuth2
google.client-id=1024798297040-als8vjdvkqrrlur3trl2m1t3cbnthmkm.apps.googleusercontent.com
